import QuestionBlock from "@/components/QuestionBlock";
import { Link } from "react-router-dom";
import LoginPageImage from "@/assets/Usage/login_page.png";
import StorySection from "@/assets/Usage/story_section.png";
import NewStory from "@/assets/Usage/new_story.png";
import ReviewBlogSection from "@/assets/Usage/review_blog_section.png";
import PendingBlogPage from "@/assets/Usage/pending_blog_page.png";
import BlogReview from "@/assets/Usage/blog_review.png";

import "./index.css";

export default function Usage() {
  return (
    <div className="p-4 leading-loose">
      <h1>Using the DTU Times Team Portal</h1>
      <p>
        This is a guide to help you understand the features of this portal and
        answer questions which may be on your mind.
      </p>
      <div>
        <h2 className="font-bold text-xl my-3">Writing blogs</h2>
        <div className="px-4">
          <ol className="list-decimal">
            <li>
              Navigate to <Link to="/">Team portal</Link> and login with your
              credentials.
              <br />
              If you don&apos;t know your password or haven&apos;t set it yet,
              you can reset it by clicking on the{" "}
              <Link to="/forgot-password">
                &quot;Forgot Password&quot; link
              </Link>
              .
              <img src={LoginPageImage} alt="Login page" />
            </li>
            <li>
              After you login, hover on the Side Navigation pane, and expand the
              &quot;Story&quot; section.
              <img src={StorySection} alt="Story section" />
            </li>
            <li>
              This new Story page contains a configuration for your entire blog.
              <img src={NewStory} alt="New story page" />
              These fields are explained below:
              <ul className="list-disc">
                <li>
                  <b>Title & Content:</b> Title is the main title of your blog
                  and the writing goes into the Content
                </li>
                <li>
                  <b>Byliner:</b> It is the introduction or a preface to your
                  blog, which is shown write above the content of your blog.
                </li>
                <li>
                  <b>Category:</b> It is the type of your blog. Your blog will
                  be shown in the Tab where you select the category on the main
                  website. (Refer:{" "}
                  <Link to="https://dtutimes.dtu.ac.in/blog">
                    DTU Times Main Website
                  </Link>
                  )
                </li>
                <li>
                  <b>Blog Image:</b> It is the image that will be shown on the
                  main website with your blog.
                </li>
                <li>
                  <b>Meta Title:</b> Should be short and crisp as this will be
                  the title visible to search engines like Google for indexing.
                </li>
                <li>
                  <b>Meta Description:</b> A short and crisp description about
                  your blog, basically a smaller byliner, which would be visible
                  to search engines like Google for indexing. (
                  <Link to="https://moz.com/learn/seo/meta-description">
                    Read More here
                  </Link>
                  )
                </li>
                <li>
                  <b>Slug:</b> Slug is the URL on which the blog is shown. For
                  example: If the slug is &quot;
                  <pre className="inline">arthur-morgan-loves-horse</pre>&quot;
                  then your blog will be published at the URL{" "}
                  <pre>
                    https://dtutimes.dtu.ac.in/blog/arthur-morgan-loves-horse
                  </pre>
                  So make it reasonable. For ease, the slug will be
                  autogenerated from the blog&apos;s title and you can refine it
                  as per your choice.
                </li>
              </ul>
            </li>
            <li>
              Once you are done, you can save your blog as &quot;Draft&quot; or
              submit it for approval.
              <br />
              <b>Drafts will only be visible to you</b> and you can edit them as
              long as you want, and delete them if not required anymore. Once
              you are finished with your draft, you can submit it for approval,
              to allow it to be reviewed by the team.
            </li>
            <li>
              After the blog is approved by the team, it will be published on
              the main website. The team can also discard your blog if changes
              are required, which will save the block back to your Draft, so you
              can make edits.
            </li>
            <li>
              You can review the status of you blog in the &quot;
              <Link to="story/your-stories/">Your Stories</Link>&quot; section
            </li>
          </ol>
        </div>
      </div>
      <hr />
      <div>
        <h2 className="font-bold text-xl my-3">Reviewing blogs</h2>
        <div className="px-4">
          Note: This section is only visible to the team members who have the
          required permissions to review blogs.
          <ol className="list-decimal">
            <li>
              Login and navigate to the{" "}
              <Link to="/story/pending-stories/">Pending Stories section</Link>
              <img src={ReviewBlogSection} />
            </li>
            <li>
              As a reviewer, you can read and review the blogs and contact the
              Author if there are any changes required in the blog before if can
              be published
              <img src={PendingBlogPage} />
              <b>
                If there are only small changes, pubslisher can change it
                directly as well using the Edit option in the menu shown in the
                image.
              </b>
            </li>
            <li>
              Here is what reading the blog will look like!
              <br />
              If you want to publish the blog you can use the publish options
              while if there are changes required you can contact the author and
              save the blog back to their draft using the &quot;Save To
              Draft&quot; option.
              <img src={BlogReview} />
            </li>
          </ol>
        </div>
      </div>
    </div>
  );
}
